### ISSUE TITLE
Get a VM on the PANUM-datacenter for hosting

### ISSUE THREAD

**Issue by dybber** [HIPERFIT/recipes#6]

**Comment by athas** [comment]
What PANUM cluster?

**Comment by dybber** [comment]
The big datacenter thing that runs all the KU websites. Maybe I'm wrong to
call it a cluster
- Martin

On 8 March 2016 at 15:57, Troels Henriksen notifications@github.com wrote:

> What PANUM cluster?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HIPERFIT/recipes/issues/6#issuecomment-193814051.

## 

Martin Dybdal

**Comment by dybber** [comment]
I have requested one through the SCIENCE-IT Service Desk-system.

I'll keep you updated.

**Comment by kfl** [comment]
@henglein said it would only take 15 min to get one.

**Comment by henglein** [comment]
I believe I said 5 months.  (Funny, Ken.  Not.)

**Comment by athas** [comment]
Using napoleon is probably a good short-term solution.

**Comment by kfl** [comment]
I honestly misheard it as you said 5 min. (And then I gave you 10 min extra margin.)

**Comment by dybber** [comment]
The request through Service Desk have been marked as "Low priority" (Priority level 4), which means "less than 5 work days". 

Let's see if they can abide by that.

**Comment by dybber** [comment]
Still no reply! 

Oleks have volunteered to put up a VM on a server paid by DIKU, that he uses for various teaching activities.

**Comment by dybber** [comment]
I bought a $5/month server from Digital Ocean, and @henglein is going to complain about the lack of response from Science IT.

I don't have time to set up password protection on Jupyter right now, but we'll get it up and running soon!
