### ISSUE TITLE
Use some code guidelines for R code

### ISSUE THREAD

**Issue by annenkov** [HIPERFIT/recipes#7]
We could use some of the existing ones, for example, this one https://google.github.io/styleguide/Rguide.xml

**Comment by oleks** [comment]
On Tue, Mar 15, 2016 at 2:23 PM, annenkov notifications@github.com wrote:

> We could use some of the existing ones, for example, this one
> https://google.github.io/styleguide/Rguide.xml

They feel a little "internal" to Google.

I also like these:

http://adv-r.had.co.nz/Style.html

I think we should merge them and clean them up.

## 

Oleks
